# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26796dc0516fd3a67cda09832838e5c42aead3a3e91c7e1ac6614894c7f92d7255ac9a7d5574eb0916a194cf7e0565d0136cd459bbc822a0dc73e04732b78e3d

test:
  secret_key_base: 2b2a996c7356ee22659e6c85371078c7d3d7fc09d4ca041168c74df67e43646c732da18a0683d922a1b194d70ac1955630ff2a27f41e383e1c2865bad9e5f737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
